name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=2.2.1
  - pip=23.3.1
  - pytest=8.0.2
  - scipy=1.12.0
  - protobuf=3.20.3
  - numpy=1.26.0
  - pip:
      - wandb==0.16.4